SkillsFundingAgency/das-platform-building-blocks

- templates/application-insights.json
Adds AppId (required for annotation using the API) to the App Insight template outputs
> App Insights to output AppId

- templates/app-service.json
To use the latest networking features available in App Service we need to ensure that we are using the correct API version.
2018-11-01 has the vnent integration property available and is also the latest version listed in the reference site.
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-11-01/sites#ipsecurityrestriction-object
> Update API version to 2018-11-01

- templates/app-service.json
Reverted addition of appServiceLocation parameter.
Location of resource group is used in the template as before, following migration of a resource group.
> Removed appServiceLocation parameter

- templates/storage-container.json
Resolves the following error
`Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The provided value 'none' for the template parameter 'publicAccess' at line '17' and column '21' is not valid. The parameter value is not part of the allowed value(s): 'Container,Blob,None'.'.`
> Fix storage container default public access

- templates/sql-server.json
Resolves the following error on deployment:
`'System' is not a valid database edition in this version of SQL Server.`
> Update api version for master database deployment

- templates/app-service.json
This PR adds a system assigned identity to app services and their associated slot (if deployed).
The change should have no impact on current deployments but will allow us to make use of the feature in the future.
> Adds system assigned identity

- templates/cosmos-db.json
Added ipRangeFilter which allows to pre-populate the cosmos firewall so it is not overwritten each release. Default value of empty string has been tested to ensure the change is none breaking.
> Added ip Range Filter

- templates/storage-account-arm.json
This allows parent ARM templates to return the value of the primary blob endpoint for storage account linked template deployments. Requirement comes from das-qna-api pipeline where the primary blob endpoint is required to be passed in as a SqlPackage variable into the DACPAC task so that it can be used to read data from the blob container.
> Add storagePrimaryEndpointsBlob output to storage-account-arm.json template

- templates/consumption-plan.json
- templates/function-app.json
- Updated `function-app.json` to check whether the App Service Plan is a Consumption Plan by checking the `computeMode`. If it's `Dynamic` which refers to a Consumption Plan type, then set `AlwaysOn` to `false`, otherwise set to `true`. If this is not set to false, then the Function App cannot be deployed onto a Consumption Plan.
- Adding new building block `consumption-plan.json`. A Consumption Plan is very specific with just ` SKU name `Y1` and tier `Dynamic` required. The `app-service-plan.json` file already has some logic relating to ASE and non-ase and I think trying to perform more logic to deploy a Consumption Plan using the existing `app-service-plan.json` might make it unreadable and messy.
> Updated function-app.json and adding new consumption-plan.json

- templates/function-app.json
The alwaysOn if statement resourceId didn't take into account whether the ASP was in a different resource group, i.e. shared ASP. It would look in the resource group of the deployment, this should now look at the resource group name passed in as parameter `appServicePlanResourceGroup`.
> Added parameters('appServicePlanResourceGroup') to alwaysOn if statement

- templates/action-group.json
Ensure that the common alert schema is always used for webhook action groups
> Enforce common alert schema for webhooks

- templates/storage-management-policy.json
Adding new building block `storage-management-policy.json`. This will allow you to apply lifecycle management rules to Storage Accounts that are General Purpose v2.
> Adding storage-management-policy.json

- templates/storage-account-arm.json
Storage Account Creation should take into account IP Addresses as well as subnet Ids
This should allow neither, either or both to be passed in.
> Storage Account Creation should take into account IP Addresses as well as subnet Ids

- templates/aks-agent-pool.json
> DASD-8326 Add maxPods parameter

- templates/app-service-v2.json
Default app service local cache size has been updated from 300 MB to 1000 MB
https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache#change-the-size-setting-in-local-cache
> Updated WEBSITE_LOCAL_CACHE_SIZEINMB to 1000 from 300

- templates/app-service-v2.json
- templates/function-app-v2.json
Adding minTlsVersion property to the `app-service-v2.json` and `function-app-v2.json` templates. By default all new App Services are minimum 1.2 however this will ensure any legacy or any possible manual amendments to TLS settings are compliant.
> Add minTlsVersion property and set to 1.2

- templates/apim/apim-group.json
- templates/apim/apim-service-with-hostnames.json
- templates/apim/apim-service.json
PR in sync with https://github.com/SkillsFundingAgency/das-shared-infrastructure/pull/67
Recent breaking Azure change - when clicking AAD button to log into the APIM developer portal a call is now sent to  `https://login.windows.net/<signInTenant>/.well-known/openid-configuration` which fails if signInTenant isn't set.
This change appears to be correlated with the APIM Groups needing an externalId that uses the tenant ID instead of the tenant primary domain.
> DASD-9045: APIM templates: Replaced tenantPrimaryDomain parameter with tenantId, added signinTenant property

- templates/storage-account-arm.json
Set allowBlobPublicAccess property to false
All das storage accounts' containers are Private access
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts?tabs=bicep#storageaccountpropertiescreateparameters
> storage-account-arm: Set allowBlobPublicAccess to false

- templates/storage-account-arm.json
Added allowSharedKeyAccess parameter defaulting to true
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts?tabs=json#storageaccountpropertiescreateparameters
> Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). The default value is null, which is equivalent to true.
Will change default to false once ARM templates consuming the building block pass the allowSharedKeyAccess parameter
> storage-account-arm: Added allowSharedKeyAccess parameter

- templates/storage-account-arm.json
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts?tabs=bicep#storageaccountpropertiescreateparameters
allowBlobPublicAccess
> Allow or disallow public access to all blobs or containers in the storage account. The default interpretation is true for this property.
> templates/storage-account-arm: Added allowBlobPublicAccess parameter

- templates/cosmos-db.json
Using 2021-05-01-preview API version of Microsoft.Insights https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2021-05-01-preview/diagnosticsettings?tabs=json so logAnalyticsDestinationType can be set to Dedicated making the destination table of logs be resource-specific as per guidance https://docs.microsoft.com/en-gb/azure/azure-monitor/essentials/resource-logs?WT.mc_id=Portal-Microsoft_Azure_Monitoring#resource-specific
>In this mode, individual tables in the selected workspace are created for each category selected in the diagnostic setting. This method is recommended since it makes it much easier to work with the data in log queries, provides better discoverability of schemas and their structure, improves performance across both ingestion latency and query times, and …
> cosmos-db.json: Added optional diagnosticSettings configuration

- templates/cosmos-db.json
- MongoRequests table correctly logs all requests (including requests from allowed subnets) - support request in progress for these to be present in the DataPlaneRequests table
- MongoRequests table will contain user information when RBAC is enabled
As mentioned in https://github.com/SkillsFundingAgency/das-platform-building-blocks/pull/255:
MSFT documentation for the MongoRequests log category on https://docs.microsoft.com/en-us/azure/cosmos-db/cosmosdb-monitor-resource-logs#choose-log-categories states:
>When you enable this category, make sure to disable DataPlaneRequests.
> cosmos-db.json: Made diagnostic settings dependent on cosmosDbType

- templates/app-service-v2.json
- templates/function-app-v2.json
FTP based deployment should be disabled as it is not used
https://docs.microsoft.com/en-gb/azure/app-service/deploy-ftp?tabs=portal
> app-service-v2, function-app-v2: Disabled ftp based deployment

- azure-pipelines-templates/build/step/app-build.yml
Build.Repository.Name predefined variable (ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services) is of the format `<organisation name>/<repository name>`
> app-build.yml: Replaced SonarCloudProjectKey parameter with dynamic generation

- azure-pipelines-templates/build/step/gitversion.yml
Updated the gitversion yaml file to not allow the use of preview versions. We recently saw a few instances of builds failing because the GitVersion task was reporting trying to retrieve the latest preview version and failed because it was unable to download the package.
> Updated the git versioning task to not use preview versions

- templates/service-bus.json
References:
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs-categories#microsoftservicebusnamespaces
https://docs.microsoft.com/en-us/azure/service-bus-messaging/monitor-service-bus-reference#runtime-audit-logs
Runtime audit logs include the `AuthKey` element - `Azure Active Directory application ID or SAS policy name that's used to authenticate to a resource.`
> templates/service-bus.json: Added RuntimeAuditLogs category

- templates/application-insights.json
- templates/log-analytics-workspace.json
App Insights output Connection string
App Insights will take an optional logAnalyticsWorkspaceId parameter
Log Analytics workspace should allow resource auth by default
> App Insights Conn String, Workspace allow resource auth

- azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml
Previously used AzurePowerShell@5 which is unneccessary as the script
this template calls only makes Azure DevOps API calls, it doesn't make
any requests with Az PowerShell.
+semver: major
> Use PS task for wait-azure-devops-deployment task

- azure-pipelines-templates/deploy/step/function-app-get-system-key.yml
Initially for use in system acceptance tests to query built-in HTTP APIs in Durable Functions to verify the state of orchestrations and entities
> Added function-app-get-system-key.yml

- azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml
Azure.Identity.AuthenticationFailedException errors are experienced if a newly created client secret is used straight away. A sleep of 1 minute prevents these errors by allowing time for backend AAD processes to complete.
> app-reg-new-temp-client-secret.yml: Added sleep of 1 minute after client secret creation

- templates/function-app-v2.json
Added optional parameter netFrameworkVersion - required when dotnet runtime is ~4 as discussed on https://learn.microsoft.com/en-us/answers/questions/835272/azure-functions-pinned-to-unsupported-dotnet-runti.html
Doesn't set netFrameworkVersion in siteConfig if no value passed in.
> function-app-v2.json: Added netFrameworkVersion parameter

- CHANGELOG.md
- azure-pipelines-templates/deploy/step/appservice-remove-ip.yml
- azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml
These changes are being made in order to allow app services including function apps to whitelist their agents onto a given app service. With new access restrictions now being applied to function apps in PP and PRD we require this in order for deployments to automated tests to succeed.
Created two new building blocks to enable pipelines to be whitelisted on app services via YAML tasks
Check over YAML structure and that the proposed code follows existing standards.
> Created two new building blocks to enable pipelines to be whitelisted on app services via YAML tasks

- CHANGELOG.md
- azure-pipelines-templates/build/step/app-build.yml
Notify pull request raisers to review vulnerable packages detected in the build's Package Scanning step
Guidance and recommended packages taken from https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md
NOTE: Install-Package with -SkipDependencies flag used until PowerShellGet v3 can be used to only install Octokit and GitHubJwt along with their dependencies - https://github.com/PowerShell/PowerShellGet/issues/487#issue-1000366159
View pipeline runs on my own personal repositories or create own GitHub app
> Added Pull Request commenting if vulnerable packages are detected +semver: minor

- CHANGELOG.md
- templates/cosmos-db.json
Azure Cosmos DB Accounts offer two backup modes: Periodic and Continuous (Point In Time Restore).
Benefits of Continuous backup mode are listed at https://learn.microsoft.com/en-us/azure/cosmos-db/migrate-continuous-backup
Set backupPolicy of Azure Cosmos DB Accounts to Continuous (30 days) mode
Reference: https://learn.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction
> templates/cosmos-db.json: Set backupPolicy to Continuous +semver: minor

- templates/aks-agent-pool.json
Add disk size property so it can override the default increasing the IOPS for a cluster.
Disk Size property added to aks-agent-pool building block
> Added osDiskSize to AKS Agent Deployment

- templates/role-assignments/role-assignment-service-bus.json
As per https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments#name:
'Role assignment resource names must be unique within the Azure Active Directory tenant, even if the scope of the role assignment is narrower.'
Set role assignment name GUID to be dependent on 3 properties to ensure uniqueness within the tenant:
- `principalId` of resource's MI which will be granted permission
- `resourceName` of resource being granted permission over
- The ID of the role assignment
> Set service bus role assignment GUID to be dependent on 3 properties to allow uniqueness

- azure-pipelines-templates/build/step/app-build.yml
Change to make a pipeline fail by default and not Continue on Error if the Package Scanning step finds any vulnerabilities. Added an optional boolean parameter to app-build.yml that allows the Package Scanning step to continue on error as per existing behaviour.
> Added error handling & parameterized continueOnError

- templates/azure-search.json
Deployment of Azure AI Search is currently disabled in West Europe. The current template supports deploying the resource to `resourceGroup().location` which will always be West Europe.
Add the ability to set the location of the resource deployment.
Confirmed the template is valid using Azure CLI --what-if
> Add location to Azure Search

- templates/app-service-plan.json
Some of the shared ASP's are set to the free tier but our shared infrastructure deployment does not support this.
Add free tier for ASP's already using it.
Tested deployment in to DTA
> Add free tier to ASP template

- templates/azure-search.json
Set AI search API access control to RBAC to prevent the use of API keys to access the service
> Set AI search API access control to RBAC

- templates/redis.json
When a private endpoint is added to an Azure Cache for Redis instance, it toggles the publicNetworkAccess property. In order to toggle this back to its original value we need to explicitly define the value in the template.
- Add publicNetworkAccess parameter for redis
- Update apiVersion to support publicNetworkAccess
- Update template schema
Check the das-shared-infrastructure deployment for the branch/PR in ADO.
> DASD-10547 - Prepare redis template for private endpoint

- azure-pipelines-templates/deploy/step/app-role-assignments.yml
This is to address Nas Migrated APIM instances RE: DASD-10990
To address app role assignments for nas migrated APIM instances
New manual-app-role-assignments YAML which will pass an extra TargetEnvironment param to the Set-AppRoleAssignments script.
[das-apim run](https://sfa-gov-uk.visualstudio.com/Apprenticeships%20Service%20Cloud%20Platform/_build/results?buildId=782485&view=logs&s=3b7ea4b9-3dd9-5196-e725-9226a8d63073) - See PreProd run here to see successful usage
> Added Manual App role assignments

- CHANGELOG.md
- azure-pipelines-templates/build/step/app-build.yml
This is to update the platform building blocks config to use the latest version of sonar cloud as the current version being 1.45.1 has deprecated packages.
Changed the solarcloud config to use the latest version 2.X
I have tested this using custom branches please see the below to see the successful run with the latest sonarcloud version.
Before - https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_build/results?buildId=784190&view=results
After - https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_build/results?buildId=789734&view=results
> Dasd 11062 sonar cloud update

- templates/app-service-plan.json
We want to be able to deploy Pv3 ASP's using the ASP template
Add option to deploy Pv3 ASP tier to ASP template
Update schema template version
> DASD-11129 - Add ASP tier option

- templates/storage-account-arm.json
As requested as part of the following ticket.
https://skillsfundingagency.atlassian.net/jira/software/c/projects/DASD/boards/391?selectedIssue=DASD-10554
Microsoft are retiring TLS version 1.0 and 1.1 for storage accounts before the end of the year.
Add the minimumTlsVersion parameter to allow greater control of setting the TLS version of storage accounts within the das-infrastructure
This can be tested on existing repo, with a deployed version of this file and see the changes on the Azure portal to check id the minimum TLS version has been changed.
> DASD-10554 - Migrate Storage Accounts to Minimum TLS version of 1.2

- CHANGELOG.md
- templates/app-service-v2.json
This change is being made to implement the health check feature on an API when the required variable has been added to the DevOps library
This has been tested and peer reviewed.
> Adding healthcheckpath to platform-building-blocks

- templates/storage-account-arm.json
Update two shared storage accounts handled by platform building blocks. The storage accounts are:
dasatsharedconfigstr
dasatsharedstr 
Set the default TLS value to 1_2
> DASD-11278/DASD-11279 - Implement minimum TLS version 1.2 into dasatsharedconfigstr and dasatsharedstr storage account

- CHANGELOG.md
- templates/aks-agent-pool.json
- templates/aks.json
Enabling encryption at host, encrypts data at the VM level before it gets encrypted at rest, increasing security of the platform
Option to enableEncryptionAtHost, setting the default to True as per the guidance from security team.
Check that new  pre-production AKS node pools have encryption at host enabled.
> added enableEncryptionAtHost property +semver: minor

- templates/app-service-hostname-binding.json
Added new template for custom hostname, used for if service has multiple hostnames they want binding to their app service.
> added app-service-hostname-binding.json template

- templates/cosmos-db.json
This change is needed to migrate all cosmos-db to TLS. This is because Microsoft are retiring TLS version 1.0 by the end of October. 
None
Ensure a working pipeline is tested with these changes, the schema is ok and the now spelling errors.
> DASD-12052 - Enforce TLS version to 1.2 for DAS cosmos accounts

- CHANGELOG.md
- templates/app-service-v2.json
Prevent random restarts/cold starts after swap slot occurs.
Add WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG
> added default app settings

- azure-pipelines-templates/build/step/app-build.yml
This change will faciitate the version upgrade from Sonarcloud v2 to v3. 
This has been tested with das-aan-hub-jobs:
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_build/results?buildId=849496&view=logs&j=0103e41a-f776-5c76-ec92-87a9d94e5e45&t=d57e4a3e-0722-5e7d-f3ea-85a6be1f7ab3
> Sonarcloud upgrade from v2 to v3

- templates/machine-learning-services/machine-learning-workspace.json
- To fufill sprint ticket https://skillsfundingagency.atlassian.net/jira/software/c/projects/DASD/boards/391?selectedIssue=DASD-11958
- To support only internal Department of Education IP's addresses when accessing the machine learning workspace on Azure 
- Update the Microsoft.MachineLearningServices/workspaces resource to an API that  supports IP whitelisting
- Introduce ARM param with a variable set in the environment specific variable group, giving control over what IP should access the resource on each environment.
> DASD-11958 - Remediation - Azure Machine Learning Workspaces should disable public network access

- CHANGELOG.md
- azure-pipelines-templates/deploy/step/get-product-app-insights.yml
- templates/application-insights-failed-requests-alert.json
- Added application insights failed request alert.
- Added get product pipeline template step. This retrieves information of the application insights used to apply the app insights alert.
> added app insights failed requests alert and get product step

- templates/apim/apim-service-named-value.json
- templates/apim/apim-service.json
- templates/keyvault-secret.json
- templates/role-assignments/role-assignment-app-insights.json
Added outputs to existing templates and added 2 templates for apim named value and role assignment to deploy and assigned a named value with a secret from key vault.
> added templates for apim app insights logger persistence

- CHANGELOG.md
- azure-pipelines-templates/deploy/step/sql-dacpac-deploy.yml
This change is to allow rotation of the SQL server password to be much easier. By fetching the key vault secret during runtime, we don't have to manually update variable groups and redeploy pipelines, instead pipelines will fetch the secret on every run. When the secret is rotated and key vault secret is updated, the pipeline will fetch the latest version of the secret, reducing the chance of downtime to DACPAC deployments.
- Added script to fetch key vault secret and set azure devops secret.
- Removed old parameter (**Breaking Change**)
> added runtime sql admin secret fetch

- templates/route-table.json
Added routes property to route table template to allow deployment of routes with route table in ARM. If no routes are passed in then default value of no routes will be used to deploy the route table.
> added routes property to route table

- azure-pipelines-templates/build/step/app-build.yml
The existing pull request commenting step was causing issues during package installation due to dependency conflicts when loading GitHub-related libraries (`Octokit`, `GitHubJwt`, etc.). This was interrupting the pipeline and preventing successful builds, even though the comment was a non-essential enhancement.
* **Commented out** the GitHub App private key download and pull request commenting PowerShell steps.
* This change temporarily disables automated PR comments related to vulnerable packages until a more stable or modern implementation can be put in place.
---
> Updated app build to remove pull request commenting

- azure-pipelines-templates/build/step/app-build.yml
The pull request commenting task has cause the pipelines to fail due to the third-party authentication kits used to execute a bot comment on a PR.  
Using JWT + REST API (GitHub) to enforce the bot comment to inform Ethan and the Author regarding outdate packages. The pipeline will also not fail if it is not able to comment and instead give a warning. 
Test against pipeline runs with a PR.
Example 
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_build/results?buildId=934403&view=logs&j=0103e41a-f776-5c76-ec92-87a9d94e5e45
> DASD-13298 - Using Powershell for PR commenting
