templates/storage-account-arm.json
Adding to the building blocks by enabling one to deploy ARM storage account.
=> Dasd 2713 storage account arm

templates/sql-server.json
"[concat('Microsoft.Sql/servers/', parameters('SQLServerName'))]"
=> Updated depends on for auditingSettings, securityAlertPolicies and administrators

README.md
Added variable usage to README:
-deploymentUrlBase
-Resource naming
=> Dasd 5001 add variable usage to readme

README.md
Added Template file name and location guidance to README
=> Added Template file name and location guidance to README

README.md
=> Added Branching strategy

.github/CODEOWNERS
Added @dalemorson as a code owner.
=> Update to CODEOWNERS

templates/function-app.json
- Added the ipSecurityRestrictions parameter to function-app.json
- Added ipSecurityRestrictions into the siteConfig section for the Microsoft.Web/Sites resource deployment
=> Added ipSecurityRestrictions support for the function-app.json template.

templates/redis.json
* Updates API Version to 2018-03-01
* Add default values to sku properties
* Return primary, secondary and a connection string as an output
=> Update API version, add defaults and return keys

README.md
Add parameter metadata guidance:
Metadata description parameter needed for top-level parameters in ARM templates.
=> Dasd 5748 add parameter metadata guidance

templates/service-bus-authorization-rule.json
Initial PR for a new template service-bus-authorization-rule.json. This template can be used to create a new authorization rule for a Service Bus namespace.
=> Added the service-bus-authorization-rule.json template

templates/aks.json
This PR adds support for basic AKS deployments. More functionality will be added when needed.
=> Add a basic aks block

templates/app-service.json
Added location parameter to app service template.
defaultValue is the resource group's location so non-disuptive.
=> Added location parameter to app service template

templates/app-service.json
Currently getting 307 status codes (Temporary redirects) when swapping slots as it is requesting to http://
=> Creates staging slot with Https Only setting

templates/storage-account-arm.json
Added Cors handling to the Arm storage Template
=> Added Cors settings to ARM storage Template

templates/cosmos-db-container-settings.json
Fix after missed parameter, after code refactor.
=> Minor Fix to cosmosDb settings

templates/function-app.json, templates/role-assignment.json
**Updates function-app.json**
- Added `functionAppApiVersion` to variables.
- Added `identity` with `SystemAssigned` to resources.
- Added `managedServiceIdentityId` to outputs.
**Updates role-assignment.json**
- Added `ServiceBusReceiver` to `assignmentType` parameter.
- Added `ServiceBusReceiver` principal ID to variables section.
- Changed Resource condition to check whether `assignmentType` parameter starts with `ServiceBus`.
=> Update function-app.json and role-assignment.json for Managed Identity

.github/CODEOWNERS
Add Nathan And Bleau to codeowners
=> Add Nathan And Bleau to codeowners

azure-pipelines-templates/dependency-check.yml
Added azure-pipelines-templates/dependency-check.yml
=> Added azure-pipelines-templates/dependency-check.yml

templates/role-assignment.json
Added Azure Service Bus Data Sender https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-service-bus-data-sender role to role-assignment.json
=> Added ServiceBusSender role to role-assignment.json

templates/service-bus-topic.json, templates/service-bus.json
Building blocks for deploying Service Bus Topics and Subscriptions
Example of ARM template:
```
{
"name": "service-bus",
"type": "Microsoft.Resources/deployments",
"apiVersion": "2017-05-10",
"properties": {
"mode": "Incremental",
"templateLink": {
"uri": "[concat(variables('deploymentUrlBase'), 'service-bus.json')]",
"contentVersion": "1.0.0.0"
},
"parameters": {
"serviceBusNamespaceName": {
"value": "[variables('serviceBusName')]"
}
}
}
},
{
"name": "[concat('service-bus-topic-', copyIndex())]",
"type": "Microsoft.Resources/deployments",
"apiVersion": "2017-05-10",
"properties": {
"mode": "Incremental",
"templateLink": {
"uri": "[concat(variables('deploymentUrlBase'), 'service-bus-topic.json')]",
"contentVersion": "1.0.0.0"
},
"parameters": {
"serviceBusNamespaceName": {
"value": …
```
=> Service bus subscriptions

templates/apim/apim-service.json
- Removed deployment of APIM managed identity key vault access policy
- No deployment of custom hostnames if apimInitialDeploy is true
=> Removed key vault access policy and no deployment of custom hostnames if apimInitialDeploy is true

azure-pipelines-templates/deploy/step/app-role-assignments.yml
Added multirepo setting for app role assignments step template
Initial use for das-apim-endpoints functionality
=> App role assignments multirepo configuration

templates/apim/apim-portal-settings.json
this building block is to enable or disable User sign up with username and password on the developer portal
=> Create apim-portal-settings building block

templates/data-factory.json
Added GitHub App configuration to the ARM Template to enable app auth workflow for github connection. 
gitHubClientId
gitHubAccountName
gitHubRepositoryName
gitHubCollaborationBranch
gitHubClientSecretKeyVaultName
keyVaultURL
=> Dasd 9171 add GitHub config to data factory template

templates/data-factory.json
Fixing the previous merge ended with a missing change. This fixes that.
=> Replaced properties section after previous merge

templates/keyvault.json
enableSoftDelete parameter still present whilst still passed in by other existing ARM templates
=> keyvault.json: Set enableSoftDelete and enablePurgeProtection to always true

templates/cdn-endpoint.json
Additional changes:
Updated deploymentTemplate $schema from 2015-01-01 to 2019-04-01
Updated apiVersion of Microsoft.Cdn resources from 2017-10-12 to 2021-06-01
=> Removed originPath property if originPath parameter is empty string

azure-pipelines-templates/deploy/step/webjob-deploy.yml
Adding option to use zip deploy for web job deployments
=> Test Wejob Deploy with zipDeploy

templates/data-share.json, templates/role-assignments/role-assignment-data-share.json
Add support for Azure Data Share in the repo
Add Azure Data Share template
Add role assignment template 
Confirmed it works using branch in a deployment and through ADO
=> DASD-9882 - Add data share resource and role assignment

templates/azure-search.json
Add some useful outputs
Add query, admin and url outputs to the template
Already tested in AT/TEST for FAA
=> Add useful outputs

templates/azure-search.json
Updating Azure Search template to be used to create the new Azure AI Search service as part of the das-shared-infrastructure pipeline.
=> DASD-10291 - Update AI Search template

templates/role-assignments/role-assignment-ai-search.json
Added AI search role Assignment Config to grant access to the resource via ARM templates
=> DASD-10292 - Added AI search role Assignment config

templates/role-assignments/role-assignment-key-vault.json
Accomodate Key Vault role assignments with new template
Added Key Vault role assignment template
Already tested with das-learner-verification-api
=> Add Key Vault Role Assignment Template

templates/app-service-plan.json
Need to add option for P0v3 tier too
Add parameters to allow P0v3 ASP tier
Tested in test sub
=> DASD-11129 - Add P0 ASP tier option

CHANGELOG.md, templates/role-assignments/role-assignment-log-analytics-workspace.json, templates/role-assignments/role-assignment-log-analytics.json
Adding a role-assignment template for Log Analytics
=> Dasd 11116 log analytics role assignment

azure-pipelines-templates/build/job/dacpac-template.yml, templates/aks-agent-pool.json, templates/aks.json
=> DASD-11212 - Enabled KEDA on AKS Cluster and added node drain timeout to node configuration

templates/aks.json
=> DASD-11212 - Setup Cluster Autoscaler profile

templates/aks.json
=> DASD-12204 - Update Node Graceful termination time

templates/route-table.json
As part of an existing ticket on the Sprint board
https://skillsfundingagency.atlassian.net/jira/software/c/projects/DASD/boards/391?selectedIssue=DASD-12305
No, UI changes. A route table ARM job has been added for a Microsoft deployments task for the shared-infrastructure 
Test against the share infrastructure repo and check if the resource has been deployed
=> DASD-12305 - Create route table ARM template

templates/aks.json
Added Diagnostic setting for AKS template
=> Added Diagnostic setting for AKS template

templates/event-hub-namespace.json
Added the missing dependsOn property for eventhub namespace diagnostc setting
=> Added the missing dependsOn property for eventhub namespace diagnostc setting

templates/application-insights-failed-requests-alert.json
Updated default number of violations to 1.
=> updated ai failed request defaults

templates/event-hub-namespace.json
Fixed spacing for diagnostic settings in Eventhub namespace template
=> Fixed spacing for diagnostic settings in Eventhub namespace template

templates/route-table.json
To fix a breaking changed, bicep does  not seem well  supported on the infrastructure 
None
See pipelines runs
=>  DASD-12525-FIX - Adjust ARM for Route table infrastructure fix

azure-pipelines-templates/deploy/step/webjob-deploy.yml
=> DASD-12600 - Updated Webjob Deploy task to stop/start webjobs using Powershell script

templates-bicep/apim-policy-fragment.bicep, templates/apim/apim-policy-fragment.json, templates/apim/apim-service-with-hostnames.json, templates/apim/apim-service.json
Added and modified templates requried to enable client authentication on APIM:
- Added policy fragment templates for both ARM and Bicep deployments.
- Modified APIM service template to add new secure gateway.
=> DASD-12694 - Enabling Client Authentication on APIM

templates/defender-for-storage.json
=> DASD-12715 - Setup Defender for Storage template

templates/role-assignments/role-assignment-key-vault.json
Added parameters to the GUID creation to allow multiple role assignments to a principal ID.
=> DASD-12694 - modified key vault role assignment name

templates/apim/apim-service.json
Required change to use the secure gateway certificate name rather than the non-secure gateway certificate
=> added secure gateway secret ID

azure-pipelines-templates/deploy/step/generate-config.yml
Needed as a sprint ticket
https://skillsfundingagency.atlassian.net/jira/software/c/projects/DASD/boards/391?selectedIssue=DASD-13006
None
Test the custom branch against a repo and either add the version param in or leave it out. If left out it will default to 1.0, if specified then it will use the value specified.
=> DASD-13089 - Uplift the Generate Configuration task in the pipeline to support custom version in the row key name.

azure-pipelines-templates/deploy/job/job-template.yml, azure-pipelines-templates/deploy/job/trigger-live-smoke-test.yml
Setup job template to be used by pipelines which will require triggering the smoke test pipeline.
=> DASD-10922 - Setup shared live smoke test suite trigger job

templates/application-insights-response-time-alert.json
Added response time alerting template
=> added response time alert template
